name: Push/Pull_request CI

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  # --- Linting process ---
  lint:
    runs-on: ubuntu-latest
    name: Linting libraries

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install linter
        run: npm install --save-dev eslint @eslint/js @types/eslint__js typescript-eslint eslint-plugin-import
      - name: Run linter
        run: npm run lint

  ubuntu:
    runs-on: ubuntu-latest
    needs: [ lint ]
    name: Ubuntu build and test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "latest"
      - name: Install packages
        run: npm ci
      - name: Build app
        run: npm run build
      - name: Run unit tests
        working-directory: ./libraries/regex-engine
        run: npm run test