name: Release CI

on:
  release

jobs:
  # --- Linting process ---
  lint:
    runs-on: ubuntu-latest
    name: Linting libraries

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install linter
        run: npm install --save-dev eslint @eslint/js @types/eslint__js typescript-eslint eslint-plugin-import
      - name: Run linter
        run: npm run lint

  # --- Test on different OS ---
  windows:
    runs-on: windows-latest
    needs: [ lint ]
    name: windows-node-${{ matrix.nodeVersion }}

    strategy:
      matrix:
        nodeVersion: [ 20, "latest" ]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodeVersion }}
      - name: Install packages
        run: npm ci
      - name: Build app
        run: npm run build
      - name: Run unit tests
        working-directory: ./libraries/regex-engine
        run: npm run test

  ubuntu:
    runs-on: ubuntu-latest
    needs: [ lint ]
    name: ubuntu-node-${{ matrix.nodeVersion }}

    strategy:
      matrix:
        nodeVersion: [ 20, "latest" ]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodeVersion }}
      - name: Install packages
        run: npm ci
      - name: Build app
        run: npm run build
      - name: Run unit tests
        working-directory: ./libraries/regex-engine
        run: npm run test

  macos:
    runs-on: macos-latest
    needs: [ lint ]
    name: macos-node-${{ matrix.nodeVersion }}

    strategy:
      matrix:
        nodeVersion: [ 20, "latest" ]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodeVersion }}
      - name: Install packages
        run: npm ci
      - name: Build app
        run: npm run build
      - name: Run unit tests
        working-directory: ./libraries/regex-engine
        run: npm run test